# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=100)),
                ('mobile_phone', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=200)),
                ('age', models.FloatField()),
            ],
        ),
    ]
